# Generated by Django 2.2.1 on 2019-05-28 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default=None, max_length=50, null=True)),
                ('address', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=255)),
                ('lastname', models.CharField(default=None, max_length=255)),
                ('age', models.IntegerField()),
                ('profession', models.CharField(default=None, max_length=255)),
                ('contact_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='cw21.ContactInfo')),
            ],
        ),
    ]
