# Generated by Django 2.2.1 on 2019-05-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cw21', '0003_auto_20190528_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='hobbies',
            field=models.ManyToManyField(related_name='persons', to='cw21.Hobbie'),
        ),
    ]
