# Generated by Django 2.2.1 on 2019-05-30 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hw21', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('release_year', models.PositiveSmallIntegerField()),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='hw21.MusicBand')),
            ],
        ),
    ]
